server:
  port: 8090

spring:
  datasource:
    druid:
      username: root
      password: 1111
      url: jdbc:mysql://localhost:3307/blog?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
      #配置Druid监控
      filter:
        stat:
          enabled: true
        wall:
          enabled: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: admin

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    log-impl:  org.apache.ibatis.logging.slf4j.Slf4jImpl
  #    逻辑删除
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)